### ISSUE TITLE
incorrect create_order method example

### ISSUE THREAD

**Issue by junw3i** [KeithSSmith/switcheo-python#16]
```switcheo_client.order(kp=kp, pair="SWTH_NEO", side="buy", price=0.0002, amount=100, use_native_token=True, order_type="limit")```

Using `kp` as the parameter in the above example returns me an error. I believe `private_key` should be the correct pararm to use.

**Comment by KeithSSmith** [comment]
You are correct!  Thought I had caught/changed all of this with the release of Ethereum integration since keypair wasn't the correct term for interacting with web3.  If you see anymore of these please point them out!

I also will use this as a reminder to get readthedocs to update properly.

**Comment by KeithSSmith** [comment]
This should be fixed in #19
