### ISSUE TITLE
Add order type: market

### ISSUE THREAD

**Issue by Devel484** [KeithSSmith/switcheo-python#20]
It is now possible to create market orders.

The new UI is able to create market order so you can see which parameter are important. The response is the same as limit order.

![bildschirmfoto vom 2018-12-11 09-40-31](https://user-images.githubusercontent.com/6864263/49788163-e22e3b80-fd28-11e8-8676-da52c413cf2c.png)

**Comment by Devel484** [comment]
I do not know if price_text and quantity_text are important.

**Comment by junw3i** [comment]
> I do not know if price_text and quantity_text are important.

They are not. You can leave price_text and quantity_text out.

**Comment by KeithSSmith** [comment]
Added as part of PR #21 

You can call this in 3 different ways:

```
AuthorizedClient.order(order_type="market")
SwitcheoClient.market_buy()
SwitcheoClient.market_sell()
```
