### ISSUE TITLE
Enhancement: Add function: getScriptHashFromAddress(address)

### ISSUE THREAD

**Issue by intsol** [KeithSSmith/switcheo-python#4]
For public facing interfaces, I suggest utilising the Public Address for *balances()* and *orders()* and providing the following helper function to convert the Public Address: String to Script Hash String. 
This usage will remove the requirement to pass private key credentials to access public information.

```
import base58
import binascii

def getScriptHashFromAddress(address):
"""
       Convert a Public Address String to a ScriptHash (Address) String.
        :param address: The Public address to convert.
        :type address: str
        :return: string containing the converted ScriptHash.

    hashBytes = binascii.hexlify(base58.b58decode_check(address))

    # reverse the bytes - disregarding the first 2
    hashStr = ""
    for x in range(-1, -len(hashBytes)+2, -2):
        hashStr += chr(hashBytes[x - 1]) + chr(hashBytes[x])

    return(hashStr) 
```

It wasn't immediately obvious where this should be added to your package, so I'll leave that to you.

**Comment by KeithSSmith** [comment]
Thank you, this was certainly high on the list of things to do and this helped immensely.  I will try to make it more clear where functions like this go but ideally we will commit these back to neo-python-core but for now they go in the switcheo.neo.utils file since it is specific to the NEO blockchain.

**Comment by KeithSSmith** [comment]
Implemented as the following

from switcheo.neo.utils import neo_get_scripthash_from_address

neo_get_scripthash_from_address(address=<address_string>)
